@startuml

	(Jogador 1) as (Use1)
	(Jogador 2) as (Use2)
	(Salva nome dos Jogadores) as (Use3)
	(Informa palavra escolhido ao jogador) as (Use5)
	(Verifica se jogador acertou a palavra) as (Use6)
	(Armazena pontuação) as (Use10)
	(Informar Vencedor) as (Use7)
	(Jogador 1 informa a primeira dica para o Jogador 2) as (Use8)
	(Jogador 2 informa seu primeiro palpite) as (Use9)

	left to right direction

	Competidores --> (Use1)
	Competidores --> (Use2)
	Competidores --> (Use8)
	Competidores --> (Use9)
	Sistema --> (Use3)
	Sistema --> (Use5)
	Sistema --> (Use6)
	Sistema --> (Use7)
	Sistema --> (Use10)


	@enduml