@startuml

	(Inserir Competidor 1) as (Use1)
	(Inserir Competidor 2) as (Use2)
	(Informar Palavra aos Competidores) as (Use3)
	(Informar ao Competidor as Dicas) as (User4)
	(Computar Pontuação) as (Use5)
	(Informar Vencedor) as (Use6)

	left to right direction

	Competidor_1 --> (Use1)
	Competidor_2 --> (Use2)
	Competidor_1 --> (User4)
	Competidor_2 --> (User4)
	Sistema --> (Use3)
	Sistema --> (Use5)
	Sistema --> (Use6)


	@enduml